import { arrayRandom } from "../utils/array-utils";

const planetNames = [
  "Orion",
  "Amia",
  "Votur",
  "Earth",
  "Apollo",
  "Sirius II",
  "2000 XP",
  "Dictys",
  "Castor",
  "Gamma",
  "Cerberus",
  "Cadmus",
  "Iris",
  "Veron",
  "Elmiobos",
  "Olroturn",
  "Cizuna",
  "Kathara",
  "Yiuter",
  "Nanov",
  "Soxenus",
  "Brovenia",
  "Trillon S16",
  "Phion S1P",
  "Adraicury",
  "Xundocury",
  "Henrypso",
  "Pusichi",
  "Hiunov",
  "Thunus",
  "Nacunov",
  "Gnaritis",
  "Chillon 268O",
  "Sonoe 6Q",
  "Unroiwei",
  "Uvutov",
  "Ingarvis",
  "Tullagua",
  "Getera",
  "Ruatune",
  "Sichizuno",
  "Boputer",
  "Dilles UUM",
  "Phore J1T5",
  "Olagantu",
  "Rostriolea",
  "Xilvone",
  "Benvars",
  "Chualiv",
  "Hilea",
  "Ceimia",
  "Thaxonus",
  "Brore QB0W",
  "Driri UD",
  "Kanocury",
  "Hillohines",
  "Nubbagua",
  "Dubuna",
  "Bulia",
  "Vater",
  "Lliotania",
  "Libethea",
  "Chuna 3AG",
  "Photh H8",
];

export const getRandomPlanetName = () => arrayRandom(planetNames);
